name: Bug Report
description: Report a bug or issue with Granola Sync
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue! Please fill out the information below to help us reproduce and fix the problem.
        
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have disabled all other plugins to confirm this is a Granola Sync issue
          required: false
          
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: "When I try to sync my meetings, the plugin shows..."
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true
      
  - type: input
    id: obsidian-version
    attributes:
      label: Obsidian Version
      description: "Found in Settings → About"
      placeholder: "e.g., 1.5.3"
    validations:
      required: true
      
  - type: input
    id: plugin-version
    attributes:
      label: Granola Sync Version
      description: "Found in Settings → Community plugins"
      placeholder: "e.g., 1.0.0"
    validations:
      required: true
      
  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: |
        Please attach any relevant error logs:
        1. Open Developer Console (Ctrl/Cmd + Shift + I)
        2. Look for errors after reproducing the issue
        3. Enable Debug Mode in plugin settings for more detailed logs
      render: shell
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information