blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/joshroman/obsidian-granola-sync/discussions
    about: Ask questions and discuss with the community
  - name: Obsidian Forum
    url: https://forum.obsidian.md/
    about: Discuss with the broader Obsidian community